# Generated by Django 5.1.7 on 2025-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagelock',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='pagelock',
            name='key',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
