# Generated by Django 5.1.7 on 2025-04-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0002_remove_pagelock_is_locked_pagelock_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageLock',
        ),
    ]
